name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - apps/worker
          - apps/web
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Changed Files
        id: changes
        run: |
          git fetch origin main
          git diff --name-only origin/main > changed_files.txt
          echo "CHANGED=$(cat changed_files.txt)" >> $GITHUB_ENV

      - name: Check if Directory Changed
        id: check
        run: |
          if grep -q "${{ matrix.directory }}" changed_files.txt; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV

      - name: Skip Deploy if Unchanged
        if: env.changed == 'false'
        run: echo "No changes in ${{ matrix.directory }}, skipping deploy."

      - name: Install Bun
        if: env.changed == 'true'
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        if: env.changed == 'true'
        run: bun install

      - name: 'Deploy to Cloudflare'
        if: env.changed == 'true'
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: 'bun'
          workingDirectory: ${{ matrix.directory }}
          command: deploy
