name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - apps/worker
          - apps/web
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for Changes
        id: check-changes
        run: |
          if git diff --name-only HEAD~1 | grep -q "^${{ matrix.directory }}/"; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
        env:
          directory: ${{ matrix.directory }}

      - name: Skip if Unchanged
        if: env.changed == 'false'
        run: echo "No changes detected for ${{ matrix.directory }}, skipping deploy."

      - name: Install Bun
        if: env.changed == 'true'
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        if: env.changed == 'true'
        run: bun install

      - name: 'Deploy to Cloudflare'
        if: env.changed == 'true'
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: 'bun'
          workingDirectory: ${{ matrix.directory }}
          command: deploy
